version: "3"

services:

  api:
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "${DB_PORT}:5432"
